from pathlib import Path
import re
p=Path('index.html');s=p.read_text(encoding='utf-8-sig')
s=s.replace('예시 데이터 · 데모','서울시 상권 자료 · 2026년 2분기').replace('예시 장소 9곳 · 매장 18곳','상권 23곳 · 집계 점포 4,374곳').replace('세 학교가 만나는 특별한 골목길 축제, 트로이카.','세 학교 주변의 실제 상권을 만나는 트로이카.').replace('체험용 가이드입니다. 장소·매장·혼잡도·혜택은 모두 예시예요.','서울시 CSV 기반 상권 가이드 · 테마와 코스는 분석 노트북의 제안입니다.')
s=s.replace('>버스킹</button>','>문화·교류</button>').replace('>감성카페</button>','>카페</button>').replace('장소 주변을 둘러보는 도보 구간 기준','권역 기준 상권 중심까지의 직선 거리 선호').replace('시간별 혼잡도','시간대별 유동인구').replace('>시뮬레이션</span>','>2026년 2분기</span>').replace('>18:00</output>','>17–21시</output>').replace('>저녁 피크타임</span>','>분기 자료 · 시간대 비중</span>').replace('혼잡도 시뮬레이션 시간','유동인구 분포 시간대').replace('max="24" value="16"','max="5" value="4"').replace('aria-valuetext="18시 00분"','aria-valuetext="17–21시"').replace('>10:00</span><span>22:00','>00시</span><span>24시').replace('시간을 18시로 초기화','시간대를 17–21시로 초기화').replace('시간을 바꾸면 여유로운 장소가 추천에 반영돼요. 실제 혼잡도는 아닙니다.','선택한 시간 구간의 유동인구 구성비를 카드와 지도 목록에서 확인하세요. 추천 순위는 시간에 따라 바뀌지 않습니다.')
s=s.replace('스탬프 0/3','탐방 목록 0/3').replace('지금, 나에게 맞는 골목','나에게 맞는 골목').replace('선택한 권역의 예시 장소입니다. 도보 시간과 위치는 경로 안내용이 아닙니다.','선택한 권역의 공식 상권 중심점입니다. 실제 매장 입구나 도보 경로를 의미하지 않습니다.').replace('<span class="status calm">여유</span><span class="status busy">붐빔</span><span class="status crowded">혼잡</span><span>혼잡도 시뮬레이션</span>','<span class="status crowded">코어</span><span class="status calm">참여</span><span class="status busy">연계</span><span>노트북의 기획 구분</span>').replace('예시 장소 지도','실제 상권 중심점 지도').replace('이 권역의 예시 장소','이 권역의 상권').replace('권역마다 다른 매력을 만나는 예시 코스. 지도에서 세 장소를 함께 살펴보세요.','분석 노트북의 세 가지 테마를 실제 상권에 연결했습니다. 축제 일정과 공연 개최 여부는 확인되지 않았습니다.')
s=s.replace('트로이카 스탬프 패스','나의 탐방 목록').replace('예시 매장 3곳에서 데모 스탬프를 모아보세요.','가보고 싶은 실제 상권을 최대 3곳 저장하세요.').replace('SAMPLE REWARD','STAMP PROGRAM · PROPOSAL').replace('15% 샘플 쿠폰','스탬프 운영 계획 · 60곳 배정안').replace('스탬프 3개를 모으면 표시돼요 · 실제 사용 불가','확정 제휴·할인 정보는 제공 자료에 없습니다.').replace('체험 대기','운영 기획').replace('이 브라우저에만 저장됩니다. 실제 방문 인증은 하지 않아요.','탐방 목록은 이 브라우저에만 저장됩니다.').replace('스탬프 초기화','탐방 목록 초기화')
a=s.index('<details class="economic-info">');b=s.index('<div class="footer-bottom">',a)
s=s[:a]+'''<details class="economic-info"><summary>데이터 출처와 추천 기준 <span>2026년 2분기 <span data-icon="plus"></span></span></summary><p>제공된 서울시 상권분석서비스 CSV 10개와 troika_stamp_analysis.ipynb를 검토했습니다. 상권 코드로 23개 지역을 연결하고, 최신 공통 분기인 2026년 2분기를 사용합니다. 점포 합계는 업종별 전체_점포_수의 합입니다. 상권배후지 점포는 중복 집계하지 않습니다.</p><p>추천은 선택 권역 안에서 업종 구성, 직선 거리 선호와 CSV로 재계산한 지수를 반영한 자체 모델입니다. 문화·교류 테마와 코스, 스탬프 배정은 노트북 기획입니다. 실시간 혼잡도, 확정 공연, 실제 제휴·쿠폰 정보는 제공하지 않습니다.</p><p>추정매출은 당월_매출_금액의 제공 업종 합계이며 실제 개별 점포 매출이 아닙니다. 시간대 비중은 길이가 다른 6개 구간의 원자료 구성비입니다. 아파트·집객시설의 누락값은 0으로 바꾸지 않습니다.</p><p><a href="https://data.seoul.go.kr/dataList/OA-15560/S/1/datasetView.do" target="_blank" rel="noopener">서울시 상권 영역</a> · <a href="https://data.seoul.go.kr/dataList/OA-15568/S/1/datasetView.do" target="_blank" rel="noopener">길단위인구</a> · <a href="https://data.seoul.go.kr/dataList/OA-15572/S/1/datasetView.do" target="_blank" rel="noopener">추정매출</a></p></details>''' +s[b:]
s=s.replace('장소·매장·혜택·혼잡도는 예시입니다. 실제 제휴나 할인권 발급을 제공하지 않습니다.','서울시 공공데이터 기반 · 권역·테마·코스는 TROIKA 기획안').replace('FESTIVAL GUIDE DEMO','NEIGHBORHOOD GUIDE').replace('이 골목의 예시 매장','이 상권의 데이터').replace('모든 매장명과 혜택은 체험용입니다. ‘데모 스탬프’를 눌러 체험해 보세요.','업종별 집계 자료이며 개별 매장 명단이 아닙니다.').replace('데모 스탬프는 실제 방문이나 위치를 확인하지 않습니다.','스탬프 배정은 운영 제안이며 확정 제휴가 아닙니다.')
p.write_text(s,encoding='utf-8')
